Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -37,13 +37,12 @@ commands:
             TARGET_GEMFILE="./gemfiles/$PARAM_APPRAISAL.gemfile.lock"
             echo $TARGET_GEMFILE
 
-            if test -f "$TARGET_GEMFILE"; then
-              APP_BUNDLER_VERSION=$(cat "$TARGET_GEMFILE" | tail -1 | tr -d " ")
-              if [ -z "$APP_BUNDLER_VERSION" ]; then
-                echo "Could not find bundler version from lockfile. Please use bundler-version parameter"
-              else
-                echo "Lock file detected bundler version $APP_BUNDLER_VERSION"
-              fi
+            APP_BUNDLER_VERSION=$(tail -1 $TARGET_GEMFILE | tr -d " ")
+            if [ -z "$APP_BUNDLER_VERSION" ]; then
+              echo "Could not find bundler version from lockfile."
+              exit 1
+            else
+              echo "Lock file detected bundler version $APP_BUNDLER_VERSION"
             fi
 
             if ! bundle version | grep -q $APP_BUNDLER_VERSION; then
